### ISSUE TITLE
Fix ansible_user_id as group in pki role

### ISSUE THREAD

**Issue by lu1as** [lu1as/ansible-kubernetes#15]
use something different than `ansible_user_id` as `pki_dest_dir_group`.
In macOS for example user and group name are not the same.

```
- name: fetch certificates
  include_role: 
    name: pki
  vars:
    pki_dest_dir: "{{kubectl_cert_folder}}"
    pki_dest_dir_owner: "{{ansible_user_id}}"
    pki_dest_dir_group: "{{ansible_user_id}}"
    inventory_hostname: client
```
